ALTER TABLE "system_config"
  ADD COLUMN "aiProviderConfigs" JSONB,
  ADD COLUMN "aiTaskConfigs" JSONB;

ALTER TYPE "OcrLogType" ADD VALUE IF NOT EXISTS 'PROMPT_IMPROVEMENT';
ALTER TYPE "OcrLogType" ADD VALUE IF NOT EXISTS 'PROMPT_TEST';
ALTER TYPE "OcrLogType" ADD VALUE IF NOT EXISTS 'TEMPLATE_BUILDER';
