INSERT INTO "template_variables" (
    "id",
    "key",
    "label",
    "description",
    "category",
    "example",
    "sortOrder",
    "active",
    "createdAt",
    "updatedAt",
    "commodity",
    "templateTypes"
) VALUES
('var_gas_001', 'GAS_TARIFF', 'Gas Access Tariff', 'Gas access tariff for the supply point', 'gas', 'RL03', 900, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_002', 'GAS_ZONE', 'Gas Zone', 'Geographic gas pricing zone', 'gas', 'Peninsula', 910, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_003', 'GAS_TELEMEASURED', 'Telemetered', 'Whether the gas supply point has remote metering', 'gas', 'NO', 920, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_004', 'GAS_BILLING_DAYS', 'Gas Billing Days', 'Number of days in the gas billing period', 'gas', '31', 930, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_005', 'GAS_CONSUMPTION_KWH', 'Gas Period Consumption', 'Gas consumption for the simulated billing period in kWh', 'gas', '12.450', 940, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_006', 'GAS_ANNUAL_CONSUMPTION_KWH', 'Gas Annual Consumption kWh', 'Estimated annual gas consumption in kWh', 'gas', '149.400', 950, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_007', 'GAS_ANNUAL_CONSUMPTION_M3', 'Gas Annual Consumption m3', 'Estimated annual gas consumption converted approximately to cubic meters', 'gas', '12.846', 960, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_008', 'GAS_IVA_RATE', 'Gas VAT Rate', 'VAT rate applied to the gas simulation', 'gas', '21,00', 970, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_009', 'GAS_HYDROCARBON_TAX_RATE', 'Hydrocarbon Tax Rate', 'Hydrocarbon tax unit rate in EUR/kWh', 'gas', '0,00234', 980, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_010', 'CURRENT_GAS_FIXED_COST', 'Current Gas Fixed Cost', 'Estimated fixed term cost for the current gas invoice', 'gas', '32,10', 1000, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_011', 'CURRENT_GAS_VARIABLE_COST', 'Current Gas Variable Cost', 'Estimated variable energy term cost for the current gas invoice', 'gas', '218,40', 1010, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_012', 'CURRENT_GAS_TAX', 'Current Hydrocarbon Tax', 'Hydrocarbon tax cost for the current gas invoice', 'gas', '29,13', 1020, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_013', 'CURRENT_GAS_RENTAL_COST', 'Current Gas Rental Cost', 'Meter rental cost for the current gas invoice', 'gas', '1,20', 1030, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_014', 'CURRENT_GAS_OTHER_COST', 'Current Gas Other Charges', 'Other charges for the current gas invoice', 'gas', '0,00', 1040, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_015', 'CURRENT_GAS_VAT', 'Current Gas VAT', 'VAT amount for the current gas invoice', 'gas', '58,97', 1050, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_016', 'CURRENT_GAS_TOTAL', 'Current Gas Total', 'Total current gas invoice amount', 'gas', '339,80', 1060, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_017', 'AXPO_GAS_FIXED_COST', 'AXPO Gas Fixed Cost', 'Fixed term cost for the selected AXPO gas offer', 'gas', '28,40', 1100, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_018', 'AXPO_GAS_VARIABLE_COST', 'AXPO Gas Variable Cost', 'Variable energy term cost for the selected AXPO gas offer', 'gas', '190,22', 1110, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_019', 'AXPO_GAS_TAX', 'AXPO Hydrocarbon Tax', 'Hydrocarbon tax cost for the selected AXPO gas offer', 'gas', '29,13', 1120, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_020', 'AXPO_GAS_RENTAL_COST', 'AXPO Gas Rental Cost', 'Meter rental cost for the selected AXPO gas offer', 'gas', '1,20', 1130, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_021', 'AXPO_GAS_OTHER_COST', 'AXPO Gas Other Charges', 'Other charges for the selected AXPO gas offer', 'gas', '0,00', 1140, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_022', 'AXPO_GAS_VAT', 'AXPO Gas VAT', 'VAT amount for the selected AXPO gas offer', 'gas', '52,28', 1150, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed'),
('var_gas_023', 'AXPO_GAS_TOTAL', 'AXPO Gas Total', 'Total invoice amount for the selected AXPO gas offer', 'gas', '301,23', 1160, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GAS', 'simulation-output,simulation-detailed')
ON CONFLICT ("key") DO UPDATE SET
    "label" = EXCLUDED."label",
    "description" = EXCLUDED."description",
    "category" = EXCLUDED."category",
    "example" = EXCLUDED."example",
    "sortOrder" = EXCLUDED."sortOrder",
    "active" = EXCLUDED."active",
    "updatedAt" = CURRENT_TIMESTAMP,
    "commodity" = EXCLUDED."commodity",
    "templateTypes" = EXCLUDED."templateTypes";
