"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _new_user_form from './new-user-form.bones.json'
import _new_agency_form from './new-agency-form.bones.json'
import _new_client_form from './new-client-form.bones.json'
import _new_base_values_form from './new-base-values-form.bones.json'
import _new_simulation_form from './new-simulation-form.bones.json'
import _edit_user_form from './edit-user-form.bones.json'
import _edit_agency_form from './edit-agency-form.bones.json'
import _edit_client_form from './edit-client-form.bones.json'
import _edit_base_values_form from './edit-base-values-form.bones.json'
import _edit_simulation_form from './edit-simulation-form.bones.json'
import _view_simulation_form from './view-simulation-form.bones.json'

registerBones({
  "new-user-form": _new_user_form,
  "new-agency-form": _new_agency_form,
  "new-client-form": _new_client_form,
  "new-base-values-form": _new_base_values_form,
  "new-simulation-form": _new_simulation_form,
  "edit-user-form": _edit_user_form,
  "edit-agency-form": _edit_agency_form,
  "edit-client-form": _edit_client_form,
  "edit-base-values-form": _edit_base_values_form,
  "edit-simulation-form": _edit_simulation_form,
  "view-simulation-form": _view_simulation_form,
})
